[package]
name = "cleanbox"
version = "0.1.0"
description = "The only inbox that actually stays clean. Simple, humble, effective email client"
authors = ["Akshit Arora"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "cleanbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# 🦀 The CleanBox Stack
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
async-imap = { version = "0.9", default-features = false, features = ["runtime-tokio"] } 
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
native-tls = "0.2"
futures-util = "0.3"

mail-parser = "0.8"
regex = "1.10"
dotenv = "0.15"
keyring = "3"
chrono = { version = "0.4", features = ["serde"] }
